version: "3.3"
services:
  ubuntu1:
    build: .
    ports:
      - "80:80"
  ubuntu2:
    build: .
    ports: 
      - "3306:3306"
  ubuntu3:
    build: .
  ansible:
    build: 
     context: .
     dockerfile: Dockerfile.ansible
  centos:
    build: 
     context: .
     dockerfile: Dockerfile.centos
    

