FROM centos:7

RUN yum  install -y openssh-server iputils-ping vim

RUN echo "root:1234" |chpasswd 

RUN echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && ssh-keygen -A

CMD ["/usr/sbin/sshd","-D"]`
